### ISSUE TITLE
Adding new algorithms for linked list

### ISSUE THREAD

**Issue by somyaguglani** [ReciHub/FunnyAlgorithms#238]
can i be assigned this issue ? i want to contribute algorithms regarding linked lists as there are almost none of those

**Comment by somyaguglani** [comment]
please look these PRs and label this as hacktoberfest2019 if possible

**Comment by ArnavNair** [comment]
Hi...I'd love to add some more algorithms for Linked Lists, namely reversing a Linked List and printing the elements of a Linked List in reverse without any additional memory usage.

**Comment by OtacilioN** [comment]
Hey @ArnavNair everyone here is welcome, you can add your algorithms!

**Comment by OtacilioN** [comment]
Hey @somyaguglani your pull requests are already merged and counting in Hacktoberfest 2019! Thanks for contributing.

**Comment by rajk1121** [comment]
@OtacilioN Please review the PR #274 . Please do tell if there are any issues with the code. It will help me to get feedback and improve the code.
Thanks.
