### ISSUE TITLE
Ellipse drawing algorithm

### ISSUE THREAD

**Issue by Vivekumar01** [ReciHub/FunnyAlgorithms#982]
Draw Ellipse using ellipse drawing algorithm in python with OpenGL library.

**Comment by Vivekumar01** [comment]
I would like to add an ellipse drawing algorithm in python. Please assign this issue to me.

**Comment by Vivekumar01** [comment]
Sir, I have completed this issue, please check the PR.

**Comment by SaiSudhaV** [comment]
Link the PR by adding the issue in it
